apiVersion: cloud.redhat.com/v1alpha1
kind: Insights
metadata:
  name: insights-collect
spec:
  image: "quay.io/jjaggars/insights-client-container:latest"
  secret: "netrc"
  entrypoint: ["/collect.sh"]
