apiVersion: cloud.redhat.com/v1alpha1
kind: Insights
metadata:
  name: insights-schedule
spec:
  image: "quay.io/jjaggars/insights-client-container:latest"
  threshold: 5  # 1440
  frequency: 5
  entrypoint: ["/gather.py"]
