apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-client-ansible-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: insights-client-ansible-operator
  template:
    metadata:
      labels:
        name: insights-client-ansible-operator
    spec:
      serviceAccountName: insights-client-ansible-operator
      containers:
        - name: insights-client-ansible-operator
          # Replace this with the built image name
          image: "{{ REPLACE_IMAGE }}"
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "insights-client-ansible-operator"
