---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: cloud.redhat.com/insights-client-ansible-operator:testing
  tasks:
  - name: Create the cloud.redhat.com/v1alpha1.Insights
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/cloud_v1alpha1_insights_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='cloud.redhat.com', api_version='v1alpha1', kind='Insights', namespace=namespace, resource_name=cr.metadata.name) }}"
    vars:
      cr: "{{ lookup('file', '/'.join([deploy_dir, 'crds/cloud_v1alpha1_insights_cr.yaml'])) | from_yaml }}"

- import_playbook: "{{ playbook_dir }}/../default/asserts.yml"
