---
- name: API Collection Job
  k8s:
    definition:
      kind: Job
      apiVersion: "batch/v1beta1"
      metadata: 
        name: "{{ meta.name }}-api-job"
        namespace: "{{ meta.namespace }}"
      spec:
        template:
          spec:
            activeDeadlineSeconds: 300
            backoffLimit: 2
            completions: 1
            parallelism: 1
            template:
              spec:
                restartPolicy: "Never"
                containers:
                  - name: "{{ meta.name }}-pod"
                    command: "{{ entrypoint }}"
                    image: "{{ image }}"
                    volumeMounts:
                      - mountPath: "/tmp/netrc"
                        name: netrc
                        readOnly: true
                volumes:
                  - name: netrc
                    secret:
                      secretName: {{ secret }}
